SIM:
  map: Town06
  render: True
  sim_dt: 0.01
  control_dt: 0.1
  t_end:
  vehicle_bp: vehicle.mini.cooper_s_2021
  n_followers: 3
  ini_gap: 10

LEAD_AGENT:
  target_speed: 100
  spawn_point: 1 #index, starts at 0
  path:
  destination: [10, 60]
  ignore_hazards: False
  hazards:
    ignore_vehicles: False
    ignore_traffic_lights: False
    ignore_stop_signs: False