SIM:
  host: 10.147.17.223
  map: Town10_opt
  port: 2000
  render: True
  sim_dt: 0.01
  control_dt: 0.1
  t_end:
  vehicle_bp: vehicle.mini.cooper_s_2021
  n_followers: 3
  ini_gap: 10

LEAD_AGENT:
  target_speed: 50
  spawn_point: 1 #index, starts at 0
  path:
  destination: [10, 60]
  ignore_hazards: False