SIM:
  map: Town05_opt
  render: True
  sim_dt: 0.01
  control_dt: 0.1
  t_end:
  vehicle_bp: vehicle.mini.cooper_s_2021
  n_followers: 3
  ini_gap: 10

LEAD_AGENT:
  type: basic #basic or cautious, normal, aggressive
  target_speed: 50 #only followed for basic agent. for Behavior types check behavior_types.py 
  spawn_point: 4 #sp index -> [-175.9413299560547, 6.477585315704346] 
  path: 
  destination: [136.1, 1.8] ##near 285. if set, agent will ignore path above..
  hazards:
    ignore_vehicles: True
    ignore_traffic_lights: True
    ignore_stop_signs: True