#Mini-Mini-F56-LCI-Cooper-S 2021
#https://www.ultimatespecs.com/pt/car-specs/Mini/125575/Mini-Mini-F56-LCI-Cooper-S.html
PHYSICS_PARAMS:
    g: 9.81  # m/s^2
    m: 1284.0  # kg
    L: 3.876 # m (length)
    W: 1.727
    H: 1.414
    Af: 2.44  # m^2 (frontal area) -> width vs height
    Cd: 0.27  # drag coefficient
    p: 1.204  # kg/m^3 (air density)
    c0: 0.0075  # rolling resistance coefficient
    c1: 2.0e-4  # rolling resistance speed-dependent coefficient
    road_grade: 0.0199973 #np.arctan(2/100) - radians (2% slope)
    v_max: 38.888 #140/3.6
    a_max: 4.209 #(100/3.6)/6.6 m/s^2 using max acc aprox from 0-100 in 6.6s -> 4.209
    a_min: -8.0 # max breaking acc

PHYSICS_PARAMS_2:
    g: 9.81  # m/s^2
    m: 1284.0  # kg
    L: 3.876 # m (length)
    W: 1.727
    H: 1.414
    Af: 2.44  # m^2 (frontal area) -> width vs height
    Cd: 0.27  # drag coefficient
    p: 1.204  # kg/m^3 (air density)
    c0: 0.009  # rolling resistance coefficient
    c1: 3.0e-4  # rolling resistance speed-dependent coefficient
    road_grade: 0.0
    v_max: 38.888 #140/3.6
    a_max: 4.209 #(100/3.6)/6.6 m/s^2 using max acc aprox from 0-100 in 6.6s -> 4.209
    a_min: -8.0 # max breaking acc
    tau: 0.3 #time constant

SIM_PARAMS:
    dt: 0.1
    h: 1.0 #s time gap 
    d_min: 2.0 #m gap when stopped (safe gap)
    d_ini: 20.0
    kp: 7
    kd: 1
    ki: 0.5    
    noise_std:
        x: 0.2
        v: 0.1
        a: 0.05